config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perfome that action"
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully log in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something worng with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have loged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Dashboard #{@user.username}"
      redirect_to user_path(@user)
      #render 'new'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfullly"
      redirect_to user_path(@user)
      #render 'new'
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    if(@user.id == current_user.id)
      session[:user_id] = nil
    end
    @user.destroy
    flash[:danger] = "User was successfully delected"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own profile"
      redirect_to root_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    redirect_to users_path if logged_in?
  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, option = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = option[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end

end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      copyright &copy; by <a href="https://www.linkedin.com/in/shrujalshah28" >Shrujal Shah</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Dashboard", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Users", users_path %></li>
         <!-- <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %> -->
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "[Admin]" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "View your profile", user_path(current_user) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this action:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-lable col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-lable col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-lable col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "Signup" : "Update account", class: 'btn btn-primary btm-lg') %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h2 align="center">Edit your account</h2>

<%= render 'form' %>

app/views/users/index.html.erb
<h2 align="center">All users</h2>

<div align="center">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="user-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <div class="user-meta-details">
            <small>Member since: <%= time_ago_in_words(user.created_at) %>, last updated: <%= time_ago_in_words(user.updated_at) %> ago</small>
          </div>
          <% if logged_in? && (current_user == user || current_user.admin?) %>
            <div class="user-action">
              <%= link_to "Edit user", edit_user_path(user), class: "btn btn-xs btn-primary" %>
              <%= link_to "Delete user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete this user?"}, class: "btn btn-xs btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h2 align="center">Sign up for Dashboard</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h2 align="center">Welcome to <%= @user.username %>'s page.</h2>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
    <div class="lable center user-body">
      Email: <%= @user.email %>
    </div>
    <div class="user-action">
      <% if logged_in? && (current_user == @user || current_user.admin?) %>
        <%= link_to "Edit user", edit_user_path(@user), class: "btn btn-md btn-primary" %>
        <%= link_to "Delete user", user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete this user?"}, class: "btn btn-md btn-danger" %>
      <% end %>
      <%= link_to "View all user", users_path, class: "btn btn-md btn-success" %>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<h1> This is About page </h1>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1>DASHBOARD</h1>
  <%= link_to "Sign up now", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %>
</div>